/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ScoutingApp;

import com.thebluealliance.api.v3.*;
import java.util.ArrayList;


public class App {



    public static void main(String[] args) {
        String authKey = ""; //Insert auth key here
        TBA tba = new TBA(authKey);
        try {
            Event newEvent = new Event(tba, "2019micmp2");
            newEvent.printTeamList();
            System.out.println("yay, it worked :)");

        } catch (Exception e) {
            //DONE: handle exception
            System.out.println(e.toString());
            System.out.println("Wow didn't work :(");
        }
        return;
    }

}
